// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  'https://qgmhqhejoilexhgwdujl.supabase.co';

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnbWhxaGVqb2lsZXhoZ3dkdWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MzIwNDksImV4cCI6MjA3NTQwODA0OX0.Szl0b3GCyMXqxLG87PCM4ikeLAVAICJ6svW3ukpcuSE';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
